name: example
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.6
  crypto: ^3.0.3
  firebase_core: ^2.31.0
  firebase_auth: ^4.19.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:


  uses-material-design: true
  assets:
    - images/
  fonts:
    - family: acme
      fonts:
        - asset: fonts/Acme-Regular.ttf
    - family: Signika
      fonts:
        - asset: fonts/signika.ttf
    - family: heebo
      fonts:
        - asset: fonts/heebo.ttf

